lista_nomes = [ 
    'Trasgo Gargalheiro',
    'Hidra de Sete Cabeças Fedorentas',
    'Fada dos Dentes Podres',
    'Gnomo Narigudo Atchim',
    'Ogro Glutão Flatulento',
    'Troll da Ponte Carcomida',
    'Ciclope Caolho Vesgo',
    'Sereia Escamosa Rouca',
    'Lobisomem Descabelado',
    'Vampiro Dentuço Anêmico',
    'Múmia Desajeitada Desatenta',
    'Fantasma Gaguejante Translúcido',
    'Górgona Despenteada',
    'Quimera Desalinhada',
    'Basilisco Miope',
    'Manticora Dentuça Mal-humorada',
    'Grifo Penoso Narigudo',
    'Kraken Tentáculos Emaranhados',
    'Leviatã Escamoso Malcheiroso',
    'Dragão Verruga Asmático',
    'Wyvern Rabugento',
    'Hipogrifo Cascudo',
    'Pégaso Emplumado',
    'Unicórnio Chifrudo Brilhante',
    'Fênix Emplumada Renascida',
    'Esfinge Enigmática',
    'Harpia Garras Afiadas',
    'Centauro Casco Rachado',
    'Sátiro Galhudo',
    'Elfo Sombrio Narigudo',
    'Orc Fedorento',
    'Goblin Obeso',
    'Mini Dragão Anão',
    'Gigante Cabeçudo',
    'Bruxa Nariguda Verruguenta',
    'Demônio Chifrudo',
    'Diabo Rabudo',
    'Anjo Caído Desalmado',
    'Hidra de Mil Cabeças',
    'Cérbero Babão',
    'Medusa Cabeluda',
    'Minotauro Chifrudo',
    'Sirene Encantadora',
    'Tritão Escamoso',
    'Nixe Aquática',
    'Kelpie Enganador',
    'Duende Travesso',
    'Diabrete Implicante',
    'Gárgula Petrificada',
    'Banshee Lamentadora',
    'Dragão Covarde',
    'Wyrm Ancião',
    'Hidra Regeneradora',
    'Beholder Olhos Múltiplos',
    'Demogorgon Príncipe Demônio',
    'Orcus Senhor dos Mortos-Vivos',
    'Yeenoghu Senhor das Feras',
    'Baphomet Senhor dos Minotauros',
    'Jubileu Senhor do Limo',
    'Zuggtmoy Senhora dos Fungos'
]
