from itens import Item

itens = [
    Item("Poção de Cura Mixuruca", 1, "Cura 25 de vida.", 2),
    Item("Sapo Morto", 0, "Sapo verde morto.", 1),
    Item("Molho de Chaves", 1, "Molho de chaves quebradas.", 1),
    Item("Espada Curta", 3, "Uma espada simples, mas eficaz", 0),
    Item("Poção de Cura Menor", 1, "Restaura 25 pontos de vida.", 0),
    Item("Escudo de Madeira", 5, "Oferece proteção básica contra ataques.", 0),
    Item("Maçã Vermelha", 0.5, "Um lanche rápido para recuperar energia.", 0),
    Item("Pergaminho de Fogo", 2, "Contém um feitiço de fogo de baixo nível.", 0),
    Item("Chave Enferrujada", 0.2, "Pode abrir alguma porta antiga.", 0),
    Item("Adaga Venenosa", 2, "Inflige dano adicional e envenena o alvo.", 0),
    Item("Anel da Sorte", 1, "Dizem que traz boa fortuna ao seu portador.", 0),
    Item("Pena de Corvo", 0.1, "Um item aparentemente inútil, mas pode ter algum significado.", 0),
    Item("Moeda de Ouro Antiga", 0.5, "Uma moeda rara e valiosa.", 0),
    Item("Mapa do Tesouro", 1, "Indica a localização de um tesouro escondido.", 0),
    Item("Amuleto da Proteção", 2, "Aumenta a resistência a ataques mágicos.", 0),
    Item("Poção de Força", 1, "Aumenta temporariamente a força do usuário.", 0),
    Item("Lanterna Mágica", 2, "Ilumina áreas escuras e revela segredos.", 0),
    Item("Livro de Enigmas", 3, "Contém enigmas desafiadores com recompensas.", 0),
    Item("Arco Longo", 4, "Uma arma de longo alcance para arqueiros habilidosos.", 0),
    Item("Flechas", 1, "Munição para o arco longo.", 0),
    Item("Poção de Invisibilidade", 2, "Torna o usuário invisível por um curto período.", 0),
    Item("Martelo de Guerra", 5, "Uma arma poderosa para guerreiros brutais.", 0),
    Item("Corda", 1, "Útil para escalar ou amarrar objetos.", 0),
    Item("Kit de Primeiros Socorros", 2, "Contém suprimentos para tratar ferimentos.", 0),
    Item("Poção de Mana", 1, "Restaura pontos de mana para conjurar feitiços.", 0),
    Item("Pedra Rúnica", 1, "Um artefato mágico com propriedades desconhecidas.", 0),
    Item("Botas de Velocidade", 2, "Aumentam a velocidade de movimento do usuário.", 0),
    Item("Luvas de Escalada", 1, "Melhoram a aderência em superfícies íngremes.", 0),
    Item("Capa da Invisibilidade", 5, "Torna o usuário invisível permanentemente.", 0),
    Item("Cajado do Mago", 4, "Aumenta o poder de feitiços mágicos.", 0),
    Item("Poção de Veneno", 1, "Inflige dano de veneno ao alvo.", 0),
    Item("Ervas Medicinais", 0.5, "Podem ser usadas para criar poções.", 0),
    Item("Diamante Bruto", 1, "Uma pedra preciosa valiosa.", 0),
    Item("Colar de Pérolas", 3, "Um item de luxo e status.", 0),
    Item("Espelho Mágico", 2, "Revela a verdadeira forma de criaturas disfarçadas.", 0),
    Item("Livro de Feitiços", 4, "Contém feitiços mágicos poderosos.", 0),
    Item("Flauta Encantada", 2, "Sua música pode acalmar feras selvagens.", 0),
    Item("Bússola Mágica", 1, "Sempre aponta para o norte verdadeiro.", 0),
    Item("Chapéu do Mago", 1, "Aumenta a inteligência e a sabedoria.", 0),
    Item("Poção do Amor", 2, "Faz com que o alvo se apaixone pelo usuário.", 0),
    Item("Saco de Moedas", 1, "Contém uma quantidade aleatória de moedas.", 0),
    Item("Tocha", 0.5, "Ilumina áreas escuras.", 0),
    Item("Faca", 1, "Uma arma pequena e versátil.", 0),
    Item("Garrafa de Vinho", 1, "Uma bebida para relaxar após a aventura.", 0),
    Item("Pedaço de Queijo", 0.5, "Um lanche rápido e nutritivo.", 0),
    Item("Pena de Fênix", 5, "Um item lendário com poderes de cura.", 0),
    Item("Ovo de Dragão", 10, "Um item raro e perigoso.", 0),
    Item("Escama de Sereia", 3, "Dizem que concede desejos.", 0),
    Item("Chifre de Unicórnio", 5, "Um ingrediente mágico poderoso.", 0),
    Item("Lágrima de Anjo", 2, "Dizem que purifica a alma.", 0),
    ]
